-- TRĂNG / public wishes database
-- Run this once in Supabase SQL Editor.
-- Public visitors may only SELECT and INSERT wishes. UPDATE/DELETE stay blocked.

create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  name varchar(40) not null,
  message varchar(180) not null,
  created_at timestamptz not null default now(),
  constraint wishes_name_length check (char_length(btrim(name)) between 1 and 40),
  constraint wishes_message_length check (char_length(btrim(message)) between 1 and 180)
);

create index if not exists wishes_created_at_idx
  on public.wishes (created_at desc);

alter table public.wishes enable row level security;

revoke all on table public.wishes from anon, authenticated;
grant select, insert on table public.wishes to anon, authenticated;
grant usage, select on sequence public.wishes_id_seq to anon, authenticated;

drop policy if exists "public can read wishes" on public.wishes;
create policy "public can read wishes"
on public.wishes
for select
to anon, authenticated
using (true);

drop policy if exists "public can submit wishes" on public.wishes;
create policy "public can submit wishes"
on public.wishes
for insert
to anon, authenticated
with check (
  char_length(btrim(name)) between 1 and 40
  and char_length(btrim(message)) between 1 and 180
);

-- Realtime: add the table to Supabase Realtime publication.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'wishes'
  ) then
    alter publication supabase_realtime add table public.wishes;
  end if;
end $$;

comment on table public.wishes is
  'Public, non-sensitive Mid-Autumn wishes displayed on the TRANG website.';

-- V3: lantern themes + public wish lights/reactions
alter table public.wishes
  add column if not exists lantern_style text not null default 'amber';

alter table public.wishes
  drop constraint if exists wishes_lantern_style_check;

alter table public.wishes
  add constraint wishes_lantern_style_check
  check (lantern_style in ('amber','jade','rose','violet','blue'));

create table if not exists public.wish_lights (
  id bigint generated by default as identity primary key,
  wish_id bigint not null references public.wishes(id) on delete cascade,
  visitor_id uuid not null,
  created_at timestamptz not null default now(),
  unique (wish_id, visitor_id)
);

create index if not exists wish_lights_wish_id_idx
  on public.wish_lights (wish_id);

alter table public.wish_lights enable row level security;

revoke all on table public.wish_lights from anon, authenticated;
grant select, insert on table public.wish_lights to anon, authenticated;
grant usage, select on sequence public.wish_lights_id_seq to anon, authenticated;

drop policy if exists "public can read wish lights" on public.wish_lights;
create policy "public can read wish lights"
on public.wish_lights
for select
to anon, authenticated
using (true);

drop policy if exists "public can light a wish once" on public.wish_lights;
create policy "public can light a wish once"
on public.wish_lights
for insert
to anon, authenticated
with check (visitor_id is not null);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='wish_lights'
  ) then
    alter publication supabase_realtime add table public.wish_lights;
  end if;
end $$;
