-- TRĂNG / public wishes database
-- Run this once in Supabase SQL Editor.
-- Public visitors may only SELECT and INSERT wishes. UPDATE/DELETE stay blocked.

create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  name varchar(40) not null,
  message varchar(180) not null,
  created_at timestamptz not null default now(),
  constraint wishes_name_length check (char_length(btrim(name)) between 1 and 40),
  constraint wishes_message_length check (char_length(btrim(message)) between 1 and 180)
);

create index if not exists wishes_created_at_idx
  on public.wishes (created_at desc);

alter table public.wishes enable row level security;

revoke all on table public.wishes from anon, authenticated;
grant select, insert on table public.wishes to anon, authenticated;
grant usage, select on sequence public.wishes_id_seq to anon, authenticated;

drop policy if exists "public can read wishes" on public.wishes;
create policy "public can read wishes"
on public.wishes
for select
to anon, authenticated
using (true);

drop policy if exists "public can submit wishes" on public.wishes;
create policy "public can submit wishes"
on public.wishes
for insert
to anon, authenticated
with check (
  char_length(btrim(name)) between 1 and 40
  and char_length(btrim(message)) between 1 and 180
);

-- Realtime: add the table to Supabase Realtime publication.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'wishes'
  ) then
    alter publication supabase_realtime add table public.wishes;
  end if;
end $$;

comment on table public.wishes is
  'Public, non-sensitive Mid-Autumn wishes displayed on the TRANG website.';


-- V3: public reactions for wishes.
create table if not exists public.wish_reactions (
  id bigint generated by default as identity primary key,
  wish_id bigint not null references public.wishes(id) on delete cascade,
  client_id uuid not null,
  reaction text not null check (reaction in ('heart','star','moon')),
  created_at timestamptz not null default now(),
  unique (wish_id, client_id, reaction)
);

create index if not exists wish_reactions_wish_id_idx
  on public.wish_reactions (wish_id);

alter table public.wish_reactions enable row level security;

revoke all on table public.wish_reactions from anon, authenticated;
grant select, insert on table public.wish_reactions to anon, authenticated;
grant usage, select on sequence public.wish_reactions_id_seq to anon, authenticated;

drop policy if exists "public can read reactions" on public.wish_reactions;
create policy "public can read reactions"
on public.wish_reactions
for select
to anon, authenticated
using (true);

drop policy if exists "public can add reactions" on public.wish_reactions;
create policy "public can add reactions"
on public.wish_reactions
for insert
to anon, authenticated
with check (reaction in ('heart','star','moon'));

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'wish_reactions'
  ) then
    alter publication supabase_realtime add table public.wish_reactions;
  end if;
end $$;

comment on table public.wish_reactions is
  'Public reactions for Mid-Autumn wishes. Anonymous clients may read and insert only.';


-- =========================================================
-- V4 / Living Sky
-- Category + independent lantern color/style + lighting + feed + reports
-- =========================================================

alter table public.wishes
  add column if not exists category varchar(16) not null default 'other',
  add column if not exists lantern_color varchar(16) not null default 'amber',
  add column if not exists lantern_style text not null default 'classic';

alter table public.wishes drop constraint if exists wishes_category_check;
alter table public.wishes
  add constraint wishes_category_check
  check (category in ('family','health','love','dream','luck','other'));

alter table public.wishes drop constraint if exists wishes_lantern_color_check;
alter table public.wishes
  add constraint wishes_lantern_color_check
  check (lantern_color in ('amber','red','jade','blue','violet'));

alter table public.wishes drop constraint if exists wishes_lantern_style_check;

update public.wishes
set lantern_style = case lantern_style
  when 'jade' then 'round'
  when 'rose' then 'lotus'
  when 'violet' then 'diamond'
  when 'blue' then 'tower'
  when 'amber' then 'classic'
  else lantern_style
end
where lantern_style in ('amber','jade','rose','violet','blue');

alter table public.wishes
  alter column lantern_style set default 'classic';

alter table public.wishes
  add constraint wishes_lantern_style_check
  check (lantern_style in ('classic','round','lotus','diamond','tower'));

create index if not exists wishes_category_created_at_idx
  on public.wishes (category, created_at desc);

create table if not exists public.wish_lights (
  id bigint generated by default as identity primary key,
  wish_id bigint not null references public.wishes(id) on delete cascade,
  visitor_id uuid not null,
  created_at timestamptz not null default now(),
  unique (wish_id, visitor_id)
);

create index if not exists wish_lights_wish_id_idx
  on public.wish_lights (wish_id);

alter table public.wish_lights enable row level security;

revoke all on table public.wish_lights from anon, authenticated;
grant select, insert on table public.wish_lights to anon, authenticated;
grant usage, select on sequence public.wish_lights_id_seq to anon, authenticated;

drop policy if exists "public can read wish lights" on public.wish_lights;
create policy "public can read wish lights"
on public.wish_lights
for select
to anon, authenticated
using (true);

drop policy if exists "public can light a wish once" on public.wish_lights;
create policy "public can light a wish once"
on public.wish_lights
for insert
to anon, authenticated
with check (visitor_id is not null);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='wish_lights'
  ) then
    alter publication supabase_realtime add table public.wish_lights;
  end if;
end $$;

drop view if exists public.wish_feed;
create view public.wish_feed
with (security_invoker = true)
as
select
  w.id,
  w.name,
  w.message,
  w.created_at,
  w.category,
  w.lantern_color,
  w.lantern_style,
  lower(w.name || ' ' || w.message) as search_text,
  coalesce(r.heart_count,0)::bigint as heart_count,
  coalesce(r.star_count,0)::bigint as star_count,
  coalesce(r.moon_count,0)::bigint as moon_count,
  coalesce(l.light_count,0)::bigint as light_count,
  (
    coalesce(r.heart_count,0)
    + coalesce(r.star_count,0)
    + coalesce(r.moon_count,0)
    + coalesce(l.light_count,0) * 2
  )::bigint as activity_score
from public.wishes w
left join (
  select
    wish_id,
    count(*) filter (where reaction='heart')::bigint as heart_count,
    count(*) filter (where reaction='star')::bigint as star_count,
    count(*) filter (where reaction='moon')::bigint as moon_count
  from public.wish_reactions
  group by wish_id
) r on r.wish_id = w.id
left join (
  select wish_id, count(*)::bigint as light_count
  from public.wish_lights
  group by wish_id
) l on l.wish_id = w.id;

grant select on public.wish_feed to anon, authenticated;

create table if not exists public.wish_reports (
  id bigint generated by default as identity primary key,
  wish_id bigint not null references public.wishes(id) on delete cascade,
  reporter_id uuid not null,
  reason varchar(32) not null default 'other',
  detail varchar(240),
  created_at timestamptz not null default now(),
  constraint wish_reports_reason_check
    check (reason in ('spam','abuse','personal_info','other')),
  constraint wish_reports_detail_length
    check (detail is null or char_length(btrim(detail)) <= 240),
  unique (wish_id, reporter_id)
);

alter table public.wish_reports enable row level security;

revoke all on table public.wish_reports from anon, authenticated;
grant insert on table public.wish_reports to anon, authenticated;
grant usage, select on sequence public.wish_reports_id_seq to anon, authenticated;

drop policy if exists "public can report a wish once" on public.wish_reports;
create policy "public can report a wish once"
on public.wish_reports
for insert
to anon, authenticated
with check (
  reporter_id is not null
  and reason in ('spam','abuse','personal_info','other')
  and (detail is null or char_length(btrim(detail)) <= 240)
);

comment on view public.wish_feed is
  'RLS-aware public aggregate feed for TRANG V4.';

comment on table public.wish_lights is
  'One public light per visitor per wish.';

comment on table public.wish_reports is
  'Public write-only moderation reports for wishes.';
