-- TRĂNG / public wishes database
-- Run this once in Supabase SQL Editor.
-- Public visitors may only SELECT and INSERT wishes. UPDATE/DELETE stay blocked.

create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  name varchar(40) not null,
  message varchar(180) not null,
  created_at timestamptz not null default now(),
  constraint wishes_name_length check (char_length(btrim(name)) between 1 and 40),
  constraint wishes_message_length check (char_length(btrim(message)) between 1 and 180)
);

create index if not exists wishes_created_at_idx
  on public.wishes (created_at desc);

alter table public.wishes enable row level security;

revoke all on table public.wishes from anon, authenticated;
grant select, insert on table public.wishes to anon, authenticated;
grant usage, select on sequence public.wishes_id_seq to anon, authenticated;

drop policy if exists "public can read wishes" on public.wishes;
create policy "public can read wishes"
on public.wishes
for select
to anon, authenticated
using (true);

drop policy if exists "public can submit wishes" on public.wishes;
create policy "public can submit wishes"
on public.wishes
for insert
to anon, authenticated
with check (
  char_length(btrim(name)) between 1 and 40
  and char_length(btrim(message)) between 1 and 180
);

-- Realtime: add the table to Supabase Realtime publication.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'wishes'
  ) then
    alter publication supabase_realtime add table public.wishes;
  end if;
end $$;

comment on table public.wishes is
  'Public, non-sensitive Mid-Autumn wishes displayed on the TRANG website.';
